### ISSUE TITLE
节点未能上线

### ISSUE THREAD

**Issue by zoukz115** [mangodager/smartx-dotnet#10]
节点掉线了，现在已经重新同步到最新高度，也执行了beruler命令，等了20分钟了，为什么还不上线？
节点地址：dgS9aBFbtE5qBvcD7AJ7xPMzB6tqMhNHW

**Comment by mangodager** [comment]
提示什么？是否使用最新的4.2.0版本？

**Comment by yuop2002cn** [comment]
已修复
