### ISSUE TITLE
节点问题

### ISSUE THREAD

**Issue by zoukz115** [mangodager/smartx-dotnet#11]
显示只有22个节点在线
![image](https://user-images.githubusercontent.com/71767976/172339309-3f880bac-65fd-4c5d-981c-aaa059cdc359.png)
为什么有23个节点确认

![image](https://user-images.githubusercontent.com/71767976/172339545-f2d0afe4-f424-497f-b39f-5627edf0dc4d.png)

**Comment by mangodager** [comment]
这是每个节点所引用的的块数，但是引用的块数并等于共识出块节点数。
