### ISSUE TITLE
请公布下我们的时间规划

### ISSUE THREAD

**Issue by wufeng1125** [mangodager/smartx-dotnet#25]
好久没什么动作了，请公布下我们的规划，时间节点

**Comment by mangodager** [comment]
At present, the smartx development team focuses on maintaining the stability of the smartx main network. After more than a year of operation, the current smartx main network has stabilized. The follow-up development team will pay attention to the recent developments in the blockchain industry and add new features, such as cross-chain, shorten block time, and add functional contracts and other functions

**Comment by wufeng1125** [comment]
那近期有什么行动么，比如跨链！上swap！或者推出什么产品
