### ISSUE TITLE
节点矿池

### ISSUE THREAD

**Issue by zoukz115** [mangodager/smartx-dotnet#5]
我的节点只运行了OnlyRuler，且poolpassword设置了密码，register设置为false。为什么还是有矿工可以接入进来？

**Comment by zoukz115** [comment]
我现在运行rulernopool好像解决了该问题，但是你能不能说明一下这几个的区别呢

**Comment by mangodager** [comment]
register不能改为false，必须为true

zoukz115 ***@***.***> 于2022年2月23日周三 11:15写道：

**Comment by mangodager** [comment]
设置密码只是为了不让其他pow矿池连接进来，不能为了矿工不能连。

zoukz115 ***@***.***> 于2022年2月23日周三 11:15写道：

**Comment by zoukz115** [comment]
好的，已经明白了。谢谢！
