### ISSUE TITLE
节点快照

### ISSUE THREAD

**Issue by 854771076** [mangodager/smartx-dotnet#6]
官网的节点快照能不能更新一下

**Comment by mangodager** [comment]
可以，但是 也是可以制作的。

fiang ***@***.***> 于2022年5月25日周三 19:57写道：

**Comment by huoyuquan** [comment]
> 官网的节点快照能不能更新一下
这里有个最新的2022-6-7的日期，拿去用吧
链接：https://pan.baidu.com/s/1z5gHv6Ax1_q8WFGRTrn1Dw 
提取码：1234
