### ISSUE TITLE
关于排名 about ranking

### ISSUE THREAD

**Issue by huoyuquan** [mangodager/smartx-dotnet#8]
如果已经是在质押取消中的账户的资产是不在排名中统计的吗？我的就没有查到，资产在前200名的。

**Comment by mangodager** [comment]
麻烦给一下您的地址，我们来排除一下是否存在bug

**Comment by wufeng1125** [comment]
> 麻烦给一下您的地址，我们来解决一下是否存在bug

fLbXf8rGepBh97THyXE4mBWWHuxSjaorp
你看我的地址就没有排名

**Comment by yuop2002cn** [comment]
已解决
